# Generated by Django 4.2.7 on 2023-11-13 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_projectadmin_is_accountant_projectadmin_is_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectadmin',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
