# Generated by Django 4.2.7 on 2023-11-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0003_remove_grade_grade_grade_finals_grade_midterm_and_more'),
        ('Accounts', '0006_alter_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='Registrar.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registrar.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
