# Generated by Django 4.2.7 on 2023-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0003_remove_grade_grade_grade_finals_grade_midterm_and_more'),
        ('Accounts', '0007_alter_student_courses_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='Registrar.course'),
        ),
    ]
