# Generated by Django 3.2.6 on 2023-11-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Accounts.student'),
            preserve_default=False,
        ),
    ]
