# Generated by Django 4.2.7 on 2023-11-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0005_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default='2023-2024', max_length=16),
            preserve_default=False,
        ),
    ]
